Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/12/2022
Var
N1, N2, S: Inteiro


Inicio
 Escreva("Informe um numero: ")
 Leia (N1)
 Escreva("Informe outro numero: ")
 Leia (N2)
 S <- N1+N2
 Escreva (" A soma e ", N1, " e ", N2, " e igual a" ,S)
Fimalgoritmo